package de.hrw.wi.business;

/**
 * 
 * @author andriesc
 *
 */
public class Car {
    // Kfz-Kennzeichen
    private String id;
    // Automarke
    private String brand;

    /**
     * 
     * @param brand
     *            the car's brand
     * @param id
     *            the car's unique identifier
     */
    public Car(String brand, String id) {
        this.id = id;
        this.brand = brand;
    }

    /**
     * 
     * @return the car's unique identifier
     */
    public String getId() {
        return id;
    }

    /**
     * 
     * @param id
     *            the car's unique identifier
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 
     * @return the car's brand
     */
    public String getBrand() {
        return brand;
    }

    /**
     * 
     * @param brand
     *            the car's brand
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * Returns a hash code value for the object calculated from the car's ID.
     * 
     * @return a hash code value for the object
     */
    @Override
    public int hashCode() {
        // generated by Eclipse
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    /**
     * Two cars are equal if and only if their ID is the same.
     * 
     * @param obj
     *            the other car to compare with
     * @return <code>true</code>, if the ID of both cars is the same, <code>false</code> otherwise
     */
    @Override
    public boolean equals(Object obj) {
        // generated by Eclipse
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Car other = (Car) obj;
        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }
        return true;
    }
}
